name: example
description: An example project to test dirk template engine
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:

dev_dependencies:
  build_runner: ^1.11.1
  dirk:
    path: ../
