builders:
  viewsBuilder:
    import: "package:dirk/builder.dart"
    builder_factories: ["viewsBuilder"]
    build_extensions: {".dart": ["views.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]