builders:
  dirkCodeBuilder:
    import: "package:dirk/builder.dart"
    builder_factories: ["dirkCodeBuilder"]
    build_extensions: {'.dirk.html': ['.dirk.dart']}
    auto_apply: dependents
    build_to: cache
    runs_before: ["dirkExportBuilder"]
    defaults:
      generate_for: ['lib/views/**']
      options:
        input_folder: lib/views/
  dirkViewsBuilder:
    import: "package:dirk/builder.dart"
    builder_factories: ["dirkViewsBuilder"]
    build_extensions: 
      'lib/$lib$': [".dart"]
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        output_file: lib/views/views.dart