name: dirk
description: A view template engine, inspired by ASP Razor. Uses code generation to dodge dart:mirrors dependency & achieve better performance.
version: 0.0.5
author: Denis Bakhtin <denis.bakhtin@gmail.com>
homepage: https://github.com/denisbakhtin/dirk

environment:
  sdk: ">=2.12.0 <3.0.0" 

dependencies:
  analyzer: ^1.5.0
  build: ^2.0.1
  build_config: ^1.0.0
  string_scanner: ^1.1.0
  build_runner: ^2.0.1
  meta: ^1.3.0
  dart_style: ^2.0.0
  path: ^1.8.0
  universal_io: ^2.0.4
  recase: ^4.0.0
  charcode: ^1.2.0
  glob: ^2.0.1
  sanitize_html: ^2.0.0
  
dev_dependencies:
  test: ^1.15.7
