// Generated by Dirk Generator, don't modify by hand

// ignore_for_file: unused_import, unused_local_variable

String IndexView() {
  String res = '';
  res += '''Sparta this is! ''';
  res += '''${(1 + 1).toString()}''';
  res += ''' == 2 Now loop paragraphs ''';
  for (var i = 1; i < 10; i++) {
    res += '''<p>Awesome printing #''';
    res += '''${i}''';
    res += '''</p> ''';
  }
  return LayoutView(res);
}

String LayoutView(String model) {
  String res = '';
  res += '''<html> ''';
  res += '''${PartialHeaderView("Awesome Website")}''';
  res += ''' <body> ''';
  res += '''${PartialSharedMenuView()}''';
  res += '''${model}''';
  res += ''' </body> </html>''';
  return res;
}

String SharedNestedView() {
  String res = '';
  res += '''<p>This is a shared piece of template</p>''';
  return LayoutView(res);
}

String PartialSharedMenuView() {
  String res = '';
  res += '''<nav><li class="nav-item">Menu item</li></nav>''';
  return res;
}

String ShowView() {
  String res = '';
  res += '''Sparta this is! ''';
  print('Show Heylo');
  return LayoutView(res);
}

String PartialHeaderView(String model) {
  String res = '';
  res += ''' <head> <title>This is head partial | ''';
  res += '''${model}''';
  res += '''</title> </head>''';
  return res;
}
