// Generated by DirkAST, don't modify

// ignore_for_file: unused_import, unused_local_variable
import 'views.dirk.dart';

String PartialHeaderView(String model) {
  String res = '';
  res += ''' <head> <title>This is head partial | ''';
  res += '''${model}''';
  res += '''</title> </head>''';
  return res;
}
