// Generated by DirkAST, don't modify

// ignore_for_file: unused_import, unused_local_variable
import 'views.dirk.dart';
import 'dart:math' as math;

String ShowView() {
  String res = '';
  var mathE = math.e;
  res += ''' <html> ''';
  res += '''${PartialHeaderView("Awesome Website")}''';
  res += ''' <body> Sparta this is! ''';
  print('Show Heylo');
  res += ''' </body> </html>''';
  return res;
}
